export const allDevices = [
    'Galaxy Note 3',
    'Galaxy Note II',
    'Galaxy S III',
    'iPad (gen 6)',
    'iPad (gen 7)',
    'iPad Mini',
    'iPad Pro 11',
    'iPhone 6',
    'iPhone 6 Plus',
    'iPhone 7',
    'iPhone 7 Plus',
    'iPhone 8',
    'iPhone 8 Plus',
    'iPhone SE',
    'iPhone X',
    'iPhone XR',
    'iPhone 11',
    'iPhone 11 Pro',
    'iPhone 11 Pro Max',
];
